# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Import Certificates and Provisioning Profile"
  private_lane :import_certificates_and_provisioning_profile do
    # アプリ本体の証明書とプロファイルをインストール
    create_keychain(
        name: "ios_app_keychain",
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1800
    )
    import_certificate(
        certificate_path: "distribution.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "ios_app_keychain",
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    install_provisioning_profile(path: "ios_app_distribution.mobileprovision")
    # Today Extension 用の証明書とプロファイルをインストール
    create_keychain(
        name: "today_extension_keychain",
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1800
    )
    import_certificate(
        certificate_path: "distribution.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "today_extension_keychain",
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    install_provisioning_profile(path: "today_extension_distribution.mobileprovision")
  end

  desc "Run unit tests"
  lane :unit_test do
    run_tests(
      scheme: "ChukyoBustime", 
      result_bundle: true
    )
  end

  desc "Upload a new build to App Store"
  lane :release do
    import_certificates_and_provisioning_profile
    build_app(
      scheme: "ChukyoBustime",
      export_options: {
        method: "app-store"
      }
    )
    deliver(
      username: ENV["APPLE_ID"],
      app_identifier: "jp.shunya.yamada.ChukyoBustime",
      submit_for_review: false,
      force: true,
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end
