name: Swift

on:
  push:
    branches: [ develop ] # 開発用に develop にプッシュ

jobs:
  build:

    runs-on: macos-latest

    steps:
    # 1. ソースのチェックアウト
    - uses: actions/checkout@v2

    # 2. GoogleService-info.plist を Secrets から取得
    - name: Setup GoogleService-info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > GoogleService-Info.plist.txt
        base64 --decode GoogleService-Info.plist.txt > Firebase/GoogleService-Info.plist

    # 証明書を Secrets から取得
    - name: Setup p12 certificate file
      run: |
        echo "${{ secrets.CERTIFICATE }}" > distribution.p12.txt
        base64 --decode distribution.p12.txt > distribution.p12

    # アプリ本体用のプロファイルを Secrets から取得
    - name: Setup iOS app provisioning profile
      run: |
        echo "${{ secrets.IOS_APP_PROVISIONING_PROFILE }}" > ios_app_distribution.mobileprovision.txt
        base64 --decode ios_app_distribution.mobileprovision.txt > ios_app_distribution.mobileprovision

    # ウィジェット用のプロファイルを Secrets から取得
    - name: Setup Today extension provisioning profile
      run: |
        echo "${{ secrets.TODAY_EXTENSION_PROVISIONING_PROFILE }}" > today_extension_distribution.mobileprovision.txt
        base64 --decode today_extension_distribution.mobileprovision.txt > today_extension_distribution.mobileprovision

    # 3. CocoaPods のキャッシュの設定
    - uses: actions/cache@v2
      with: 
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    # 4. キャッシュから Pods ファイルを取得、なければそのまま pod install して自前ビルド
    - name: Install CocoaPods frameworks and build with custom scripts
      if: steps.cache-cocoapods.outputs.cache-hit != 'true'
      run: pod install && sh Scripts/pods_build.sh

    # 5. Carthage のキャッシュの設定
    - uses: actions/cache@v2
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-

    # 6. キャッシュから Carthage 関連のファイルを取得、なければそのまま carhage update
    - name: Install Carthage frameworks
      run: carthage bootstrap --platform iOS --cache-builds

    # 7. Firebase App Distribution にビルドを追加
    - name: Push a new beta build to Firebase App Distribution
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        bundle exec fastlane adhoc
