name: Test

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ develop ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    # 1. ソースのチェックアウト
    - uses: actions/checkout@v2

    # 2. GoogleService-info.plist を Secrets から取得
    - name: Setup GoogleService-info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > GoogleService-Info.plist.txt
        base64 -Dd -i GoogleService-Info.plist.txt -o App/App/GoogleService-Info.plist

    # 3. Unit test を Fastlane で実行( Swift Macro の許諾突破用にスクリプトも実行 )
    - name: Run unit test
      run: |
        defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        fastlane unit_test
