name: Test

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ develop ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    # 1. ソースのチェックアウト
    - uses: actions/checkout@v2

    # 2. GoogleService-info.plist を Secrets から取得
    - name: Setup GoogleService-info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > GoogleService-Info.plist.txt
        base64 -d GoogleService-Info.plist.txt > App/App/GoogleService-Info.plist

    # 3. Unit test を Fastlane で実行
    - name: Run unit test
      run: |
        fastlane unit_test
