name: Test

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ develop ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    # ソースのチェックアウト
    - uses: actions/checkout@v2

    # GoogleService-info.plist を Secrets から取得
    - name: Setup GoogleService-info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > GoogleService-Info.plist.txt
        base64 -Dd -i GoogleService-Info.plist.txt -o App/App/GoogleService-Info.plist

    # Xcode のバージョンを 16.1 に指定
    - name: Select Xcode version 16.1
      run: sudo xcode-select -s '/Applications/Xcode_16.1.app/Contents/Developer'

    # Unit test を Fastlane で実行
    - name: Run unit test
      run: |
        fastlane unit_test
